<?php

use Illuminate\Database\Seeder;

class InputsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    // 1 => Personajes
    // 2 => Escenarios
    // 3 => Objetos
    // 4 => Situaciones
    // 5 => Temas
    public function run()
    {
      DB::table('inputs')->insert([
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un anciano', 'name_trans' => 'anciano', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un adolescente', 'name_trans' => 'adolescente', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un artista', 'name_trans' => 'artista', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un músico', 'name_trans' => 'musico', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un niño', 'name_trans' => 'nino', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un hombre mayor', 'name_trans' => 'hombre mayor', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'una anciana', 'name_trans' => 'anciana', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'una adolescente', 'name_trans' => 'adolescente', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'una niña', 'name_trans' => 'nina', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'una mujer mayor', 'name_trans' => 'mujer mayor', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un bebé', 'name_trans' => 'bebe', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'una mujer', 'name_trans' => 'mujer', 'generico' => 1],
        ['tipo_id' => 1, 'sexo' => 0, 'name' => 'un hombre', 'name_trans' => 'hombre', 'generico' => 1],

        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'castillo', 'name_trans' => 'castillo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'parada del autobús', 'name_trans' => 'parada_del_autobus', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'jardín', 'name_trans' => 'jardin', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'patio de una casa', 'name_trans' => 'patio_casa', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'calle', 'name_trans' => 'calle', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'librería', 'name_trans' => 'libreria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'barbería', 'name_trans' => 'barberia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'banco', 'name_trans' => 'banco', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'biblioteca', 'name_trans' => 'biblioteca', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'supermercado', 'name_trans' => 'supermercado', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'mercado', 'name_trans' => 'mercado', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'gasolinera', 'name_trans' => 'gasolinera', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cuadra', 'name_trans' => 'cuadra', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'oficina', 'name_trans' => 'oficina', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'bolera', 'name_trans' => 'bolera', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'iglesia', 'name_trans' => 'iglesia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'restaurante', 'name_trans' => 'restaurante', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'escuela', 'name_trans' => 'escuela', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'farmacia', 'name_trans' => 'farmacia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'acuario', 'name_trans' => 'acuario', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'zoo', 'name_trans' => 'zoo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'plaza', 'name_trans' => 'plaza', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'laberinto', 'name_trans' => 'laberinto', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'despacho', 'name_trans' => 'despacho', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'horno', 'name_trans' => 'horno', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'veranda', 'name_trans' => 'veranda', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'celda', 'name_trans' => 'celda', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'prisión', 'name_trans' => 'prision', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'hotel', 'name_trans' => 'hotel', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'buhardilla', 'name_trans' => 'buhardilla', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'asilo', 'name_trans' => 'asilo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'gran salón', 'name_trans' => 'gran_salon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'vestuario', 'name_trans' => 'vestuario', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'patio', 'name_trans' => 'patio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'pórtico', 'name_trans' => 'portico', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'despensa', 'name_trans' => 'despensa', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'submarino', 'name_trans' => 'submarino', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'avión', 'name_trans' => 'avion', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'yate', 'name_trans' => 'yate', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'avioneta', 'name_trans' => 'avioneta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'helicóptero', 'name_trans' => 'helicoptero', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'lavadero', 'name_trans' => 'lavadero', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'tren', 'name_trans' => 'tren', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'vestíbulo', 'name_trans' => 'vestibulo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'salita', 'name_trans' => 'salita', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'comedor', 'name_trans' => 'comedor', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'baño', 'name_trans' => 'bano', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'terma', 'name_trans' => 'terma', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'velatorio', 'name_trans' => 'velatorio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'ático', 'name_trans' => 'atico', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'desván', 'name_trans' => 'desvan', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'parque', 'name_trans' => 'parque', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'salón', 'name_trans' => 'salon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'galería', 'name_trans' => 'galeria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'peluquería', 'name_trans' => 'peluqueria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'gimnasio', 'name_trans' => 'gimnasio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'templo', 'name_trans' => 'templo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'pirámide', 'name_trans' => 'piramide', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'anfiteatro', 'name_trans' => 'anfiteatro', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'faro', 'name_trans' => 'faro', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'casino', 'name_trans' => 'casino', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'teatro', 'name_trans' => 'teatro', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'torre', 'name_trans' => 'torre', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'estadio', 'name_trans' => 'estadio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'mezquita', 'name_trans' => 'mezquita', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'palacio', 'name_trans' => 'palacio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'club', 'name_trans' => 'club', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'fábrica', 'name_trans' => 'fabrica', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'molino', 'name_trans' => 'molino', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'bote', 'name_trans' => 'bote', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'barco', 'name_trans' => 'barco', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'velero', 'name_trans' => 'velero', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'acueducto', 'name_trans' => 'acueducto', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'granero', 'name_trans' => 'granero', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'asamblea', 'name_trans' => 'asamblea', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'establo', 'name_trans' => 'establo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'bar de alterne', 'name_trans' => 'bar_de_alterne', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'granja', 'name_trans' => 'granja', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cripta', 'name_trans' => 'cripta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'bodega', 'name_trans' => 'bodega', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'pabellón', 'name_trans' => 'pabellon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'pagoda', 'name_trans' => 'pagoda', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'estudio', 'name_trans' => 'estudio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'convento', 'name_trans' => 'convento', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'pista de patinaje', 'name_trans' => 'pista_de_patinaje', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'sinagoga', 'name_trans' => 'sinagoga', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'sótano', 'name_trans' => 'sotano', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'almacén', 'name_trans' => 'almacen', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'prostíbulo', 'name_trans' => 'prostibulo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'casa de muñecas', 'name_trans' => 'casa_de_munecas', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'casa en un árbol', 'name_trans' => 'casa_en_un_arbol', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'estación de policía', 'name_trans' => 'estacion_de_policia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'monasterio', 'name_trans' => 'monasterio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'aseo', 'name_trans' => 'aseo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'letrina', 'name_trans' => 'letrina', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'residencia', 'name_trans' => 'residencia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'planta nuclear', 'name_trans' => 'planta_nuclear', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'motel', 'name_trans' => 'motel', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'sala de reuniones', 'name_trans' => 'sala_de_reuniones', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'minarete', 'name_trans' => 'minarete', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'mausoleo', 'name_trans' => 'mausoleo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'mansión', 'name_trans' => 'mansion', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'laboratorio', 'name_trans' => 'laboratorio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'iglú', 'name_trans' => 'iglu', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'jaula', 'name_trans' => 'jaula', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'muelle', 'name_trans' => 'muelle', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cobertizo', 'name_trans' => 'cobertizo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'choza', 'name_trans' => 'choza', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'refugio', 'name_trans' => 'refugio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'hall', 'name_trans' => 'hall', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'hostal', 'name_trans' => 'hostal', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'sauna', 'name_trans' => 'sauna', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'tipi', 'name_trans' => 'tipi', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'madriguera', 'name_trans' => 'madriguera', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'logia', 'name_trans' => 'logia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'consejería', 'name_trans' => 'consejeria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'portería', 'name_trans' => 'porteria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'sede', 'name_trans' => 'sede', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cuartel', 'name_trans' => 'cuartel', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'casa encantada', 'name_trans' => 'casa_encantada', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cenador', 'name_trans' => 'cenador', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'mirador', 'name_trans' => 'mirador', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'kiosko', 'name_trans' => 'kiosko', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'glorieta', 'name_trans' => 'glorieta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'fortaleza', 'name_trans' => 'fortaleza', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'fundición', 'name_trans' => 'fundicion', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'embajada', 'name_trans' => 'embajada', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cúpula', 'name_trans' => 'cupula', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'dormitorio', 'name_trans' => 'dormitorio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'dársena', 'name_trans' => 'darsena', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'terminal', 'name_trans' => 'terminal', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'garaje', 'name_trans' => 'garaje', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'forja', 'name_trans' => 'forja', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'invernadero', 'name_trans' => 'invernadero', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'capilla', 'name_trans' => 'capilla', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'catacumba', 'name_trans' => 'catacumba', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cabaña', 'name_trans' => 'cabana', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'búnker', 'name_trans' => 'bunker', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'barracón', 'name_trans' => 'barracon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'armería', 'name_trans' => 'armeria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'playa', 'name_trans' => 'playa', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'reactor nuclear', 'name_trans' => 'reactor_nuclear', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'fuerte', 'name_trans' => 'fuerte', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'santuario', 'name_trans' => 'santuario', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'ermita', 'name_trans' => 'ermita', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'ópera', 'name_trans' => 'opera', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'corte', 'name_trans' => 'corte', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'carnicería', 'name_trans' => 'carniceria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'taller', 'name_trans' => 'taller', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'isla', 'name_trans' => 'isla', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'atolón', 'name_trans' => 'atolon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'arroyo', 'name_trans' => 'arroyo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'panadería', 'name_trans' => 'panaderia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'juzgado', 'name_trans' => 'juzgado', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'ciénaga', 'name_trans' => 'cienaga', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'golfo', 'name_trans' => 'golfo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'oasis', 'name_trans' => 'oasis', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'pradera', 'name_trans' => 'pradera', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cima', 'name_trans' => 'cima', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'tundra', 'name_trans' => 'tundra', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'mar', 'name_trans' => 'mar', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'habitación', 'name_trans' => 'habitacion', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'pasadizo', 'name_trans' => 'pasadizo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'estanque', 'name_trans' => 'estanque', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'casa de campo', 'name_trans' => 'casa_de_campo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'meseta', 'name_trans' => 'meseta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'balcón', 'name_trans' => 'balcon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cascada', 'name_trans' => 'cascada', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'acantilado', 'name_trans' => 'acantilado', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cráter', 'name_trans' => 'crater', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'glaciar', 'name_trans' => 'glaciar', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'encrucijada', 'name_trans' => 'encrucijada', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cañón', 'name_trans' => 'canon', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'canal', 'name_trans' => 'canal', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'colina', 'name_trans' => 'colina', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'volcán', 'name_trans' => 'volcan', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'gruta', 'name_trans' => 'gruta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'istmo', 'name_trans' => 'istmo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'iceberg', 'name_trans' => 'iceberg', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'bosque', 'name_trans' => 'bosque', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'valle', 'name_trans' => 'valle', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'estrecho', 'name_trans' => 'estrecho', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'abismo', 'name_trans' => 'abismo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'sima', 'name_trans' => 'sima', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cueva', 'name_trans' => 'cueva', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'sueño', 'name_trans' => 'sueno', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'mundo diferente', 'name_trans' => 'mundo_diferente', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'risco', 'name_trans' => 'risco', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'ensenada', 'name_trans' => 'ensenada', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'bahía', 'name_trans' => 'bahia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'pantano', 'name_trans' => 'pantano', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'alcantarilla', 'name_trans' => 'alcantarilla', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'parlamento', 'name_trans' => 'parlamento', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cuenca', 'name_trans' => 'cuenca', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'casa', 'name_trans' => 'casa', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cementerio', 'name_trans' => 'cementerio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'fuente', 'name_trans' => 'fuente', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'río', 'name_trans' => 'rio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'lago', 'name_trans' => 'lago', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'museo', 'name_trans' => 'museo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'piso', 'name_trans' => 'piso', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'puente', 'name_trans' => 'puente', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'dique', 'name_trans' => 'dique', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'edificio', 'name_trans' => 'edificio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'academia', 'name_trans' => 'academia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'abadía', 'name_trans' => 'abadia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'pescadería', 'name_trans' => 'pescaderia', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'tintorería', 'name_trans' => 'tintoreria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'puerto', 'name_trans' => 'puerto', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'tienda', 'name_trans' => 'tienda', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'pueblo', 'name_trans' => 'pueblo', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'suburbio', 'name_trans' => 'suburbio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'aldea', 'name_trans' => 'aldea', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'villa', 'name_trans' => 'villa', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'ferretería', 'name_trans' => 'ferreteria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'hangar', 'name_trans' => 'hangar', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'aeropuerto', 'name_trans' => 'aeropuerto', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'rascacielos', 'name_trans' => 'rascacielos', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'posta', 'name_trans' => 'posta', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'catedral', 'name_trans' => 'catedral', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'taberna', 'name_trans' => 'taberna', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'bar', 'name_trans' => 'bar', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'apartamento', 'name_trans' => 'apartamento', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'chalet', 'name_trans' => 'chalet', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'estación', 'name_trans' => 'estacion', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cafetería', 'name_trans' => 'cafeteria', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'hospital', 'name_trans' => 'hospital', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'ultramarinos', 'name_trans' => 'ultramarinos', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'cine', 'name_trans' => 'cine', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'centro comercial', 'name_trans' => 'centro_comercial', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'universidad', 'name_trans' => 'universidad', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 0, 'name' => 'observatorio', 'name_trans' => 'observatorio', 'generico' => 1],
        ['tipo_id' => 2, 'sexo' => 1, 'name' => 'cocina', 'name_trans' => 'cocina', 'generico' => 1],

        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'espada', 'name_trans' => 'espada', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'pincel', 'name_trans' => 'pincel', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'chocolate', 'name_trans' => 'chocolate', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cuerda', 'name_trans' => 'cuerda', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'coche', 'name_trans' => 'coche', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cuchara', 'name_trans' => 'cuchara', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'mondadientes', 'name_trans' => 'mondadientes', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'jarrón', 'name_trans' => 'jarron', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'goma', 'name_trans' => 'goma', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'manzana', 'name_trans' => 'manzana', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'hilo', 'name_trans' => 'hilo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'guante', 'name_trans' => 'guante', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'peonza', 'name_trans' => 'peonza', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cometa', 'name_trans' => 'kite', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cometa', 'name_trans' => 'cometa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'juguete', 'name_trans' => 'juguete', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'lámpara', 'name_trans' => 'lampara', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'mapa', 'name_trans' => 'mapa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'garra', 'name_trans' => 'garra', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'pergamino', 'name_trans' => 'pergamino', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'bebida', 'name_trans' => 'bebida', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'orbe', 'name_trans' => 'orbe', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'testamento', 'name_trans' => 'testamento', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'pluma', 'name_trans' => 'pluma', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'globo', 'name_trans' => 'globo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'tótem', 'name_trans' => 'totem', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'piedra', 'name_trans' => 'piedra', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'ofrenda', 'name_trans' => 'ofrenda', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'recuerdo', 'name_trans' => 'recuerdo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'urna', 'name_trans' => 'urna', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'estrella', 'name_trans' => 'estrella', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'broche', 'name_trans' => 'broche', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'ectoplasma', 'name_trans' => 'ectoplasma', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'rama', 'name_trans' => 'rama', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'postal', 'name_trans' => 'postal', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'calavera', 'name_trans' => 'calavera', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cadena', 'name_trans' => 'cadena', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'diente', 'name_trans' => 'diente', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'caja', 'name_trans' => 'caja', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cojín', 'name_trans' => 'cojin', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'copa', 'name_trans' => 'copa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'paraguas', 'name_trans' => 'paraguas', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'vial', 'name_trans' => 'vial', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'fósil', 'name_trans' => 'fosil', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'huevo', 'name_trans' => 'huevo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'estatuilla', 'name_trans' => 'estatuilla', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'máscara', 'name_trans' => 'mascara', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'gema', 'name_trans' => 'gema', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'hueso', 'name_trans' => 'hueso', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'brazalete', 'name_trans' => 'brazalete', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'bastón', 'name_trans' => 'baston', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cargador', 'name_trans' => 'cargador', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'esponja', 'name_trans' => 'esponja', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'chal', 'name_trans' => 'chal', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'tablet', 'name_trans' => 'tablet', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'trofeo', 'name_trans' => 'trofeo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cruz', 'name_trans' => 'cruz', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'abrelatas', 'name_trans' => 'abrelatas', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'móvil', 'name_trans' => 'movil', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'adaptador', 'name_trans' => 'adaptador', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'pulsera', 'name_trans' => 'pulsera', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'flauta', 'name_trans' => 'flauta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'poción', 'name_trans' => 'pocion', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'arco', 'name_trans' => 'arco', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'flecha', 'name_trans' => 'flecha', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'varita', 'name_trans' => 'varita', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'boomerang', 'name_trans' => 'boomerang', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'escudo', 'name_trans' => 'escudo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'sartén', 'name_trans' => 'sarten', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'toalla', 'name_trans' => 'toalla', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'brócoli', 'name_trans' => 'brocoli', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'lavadora', 'name_trans' => 'lavadora', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'muñeca', 'name_trans' => 'muneca', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'USB', 'name_trans' => 'USB', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cristal', 'name_trans' => 'cristal', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'pintalabios', 'name_trans' => 'pintalabios', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'crema', 'name_trans' => 'crema', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'casco', 'name_trans' => 'casco', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'galleta', 'name_trans' => 'galleta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'pajarita', 'name_trans' => 'pajarita', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'armadura', 'name_trans' => 'armadura', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'sofá', 'name_trans' => 'sofa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'carnet', 'name_trans' => 'carnet', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'ordenador', 'name_trans' => 'ordenador', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'dibujo', 'name_trans' => 'dibujo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'escultura', 'name_trans' => 'escultura', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'reloj', 'name_trans' => 'reloj', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'peluche', 'name_trans' => 'peluche', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'tarjeta', 'name_trans' => 'tarjeta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'champú', 'name_trans' => 'champu', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'vela', 'name_trans' => 'vela', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'libro', 'name_trans' => 'libro', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'carta', 'name_trans' => 'carta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'paquete', 'name_trans' => 'paquete', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'ambientador', 'name_trans' => 'ambientador', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'papel', 'name_trans' => 'papel', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'lata', 'name_trans' => 'lata', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'bolsa', 'name_trans' => 'bolsa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'balón', 'name_trans' => 'balon', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'ticket', 'name_trans' => 'ticket', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cepillo', 'name_trans' => 'cepillo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'radio', 'name_trans' => 'radio', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'espejo', 'name_trans' => 'espejo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'pañuelo', 'name_trans' => 'panuelo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'flor', 'name_trans' => 'flor', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cinta adhesiva', 'name_trans' => 'cinta_adhesiva', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'moneda', 'name_trans' => 'moneda', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'instrumento', 'name_trans' => 'instrumento', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'piano', 'name_trans' => 'piano', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cartera', 'name_trans' => 'cartera', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'cámara', 'name_trans' => 'camara', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'marcapáginas', 'name_trans' => 'marcapaginas', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'posavasos', 'name_trans' => 'posavasos', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'zapatillas de ir por casa', 'name_trans' => 'zapatillas_de_ir_por_casa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'termómetro', 'name_trans' => 'termometro', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cuchillo', 'name_trans' => 'cuchillo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'llavero', 'name_trans' => 'llavero', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'planta', 'name_trans' => 'planta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'balanza', 'name_trans' => 'balanza', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'tubo fosforescente', 'name_trans' => 'tubo_fosforescente', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'azucarillo', 'name_trans' => 'azucarillo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'periódico', 'name_trans' => 'periodico', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'patito de goma', 'name_trans' => 'patito_de_goma', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'camiseta', 'name_trans' => 'camiseta', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'anillo', 'name_trans' => 'anillo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'columpio', 'name_trans' => 'columpio', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'bomba', 'name_trans' => 'bomba', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'vestido', 'name_trans' => 'vestido', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'zapato', 'name_trans' => 'zapato', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'bolso', 'name_trans' => 'bolso', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'tapón', 'name_trans' => 'tapon', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'CD', 'name_trans' => 'CD', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cuadro', 'name_trans' => 'cuadro', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'mando', 'name_trans' => 'mando', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'aguja', 'name_trans' => 'aguja', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'bolígrafo', 'name_trans' => 'boligrafo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'martillo', 'name_trans' => 'martillo', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'pinza', 'name_trans' => 'pinza', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'gafa', 'name_trans' => 'gafa', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'nevera', 'name_trans' => 'nevera', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'calcetín', 'name_trans' => 'calcetin', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'álbum', 'name_trans' => 'álbum', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'percha', 'name_trans' => 'percha', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'lápiz', 'name_trans' => 'lapiz', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'brújula', 'name_trans' => 'brujula', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'baúl', 'name_trans' => 'baul', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 0, 'name' => 'cofre', 'name_trans' => 'cofre', 'generico' => 1],
        ['tipo_id' => 3, 'sexo' => 1, 'name' => 'llave', 'name_trans' => 'llave', 'generico' => 1],

        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'súplica', 'name_trans' => 'suplica', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'persecución', 'name_trans' => 'persecucion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'rescate', 'name_trans' => 'rescate', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'desastre', 'name_trans' => 'desastre', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'infortunio', 'name_trans' => 'infortunio', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'escape', 'name_trans' => 'escape', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'revuelta', 'name_trans' => 'revuelta', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'iniciativa', 'name_trans' => 'iniciativa', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'metamorfosis', 'name_trans' => 'metamorfosis', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'invalidez', 'name_trans' => 'invalidez', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'coincidencia', 'name_trans' => 'coincidencia', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'mala suerte', 'name_trans' => 'mala_suerte', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'buena suerte', 'name_trans' => 'buena_suerte', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'impotencia', 'name_trans' => 'impotencia', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'secuestro', 'name_trans' => 'secuestro', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'enigma', 'name_trans' => 'enigma', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'recuperación de una posesión', 'name_trans' => 'recuperacion_de_una_posesion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'búsqueda', 'name_trans' => 'busqueda', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'venganza', 'name_trans' => 'venganza', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'enemistad', 'name_trans' => 'enemistad', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'aventura', 'name_trans' => 'aventura', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'imprudencia', 'name_trans' => 'imprudencia', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'sufrimiento', 'name_trans' => 'sufrimiento', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'descubrimiento', 'name_trans' => 'descubrimiento', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'sacrificio', 'name_trans' => 'sacrificio', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'maduración', 'name_trans' => 'maduracion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'ausencia', 'name_trans' => 'ausencia', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'transformación', 'name_trans' => 'transformacion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'prohibición', 'name_trans' => 'prohibicion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'pérdida', 'name_trans' => 'perdida', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'juicio erróneo', 'name_trans' => 'juicio_erroneo', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'ambición', 'name_trans' => 'ambicion', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'deshonor', 'name_trans' => 'deshonor', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'ruptura de un tabú', 'name_trans' => 'ruptura_de_un_tabu', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'locura', 'name_trans' => 'locura', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'adulterio', 'name_trans' => 'adulterio', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 1, 'name' => 'rivalidad', 'name_trans' => 'rivalidad', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'pago de una deuda', 'name_trans' => 'pago_deuda', 'generico' => 1],
        ['tipo_id' => 4, 'sexo' => 0, 'name' => 'crimen', 'name_trans' => 'crimen', 'generico' => 1],

        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el conocimiento', 'name_trans' => 'conocimiento', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la supervivencia', 'name_trans' => 'supervivencia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la raza', 'name_trans' => 'raza', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el hambre', 'name_trans' => 'hambre', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el racismo', 'name_trans' => 'racismo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el sexo', 'name_trans' => 'sexo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el ser humano', 'name_trans' => 'ser_humano', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el bien', 'name_trans' => 'bien', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la deidad', 'name_trans' => 'deidad', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la decepción', 'name_trans' => 'decepcion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el conformismo', 'name_trans' => 'conformismo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el deber', 'name_trans' => 'deber', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el mal', 'name_trans' => 'mal', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la muerte', 'name_trans' => 'muerte', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la búsqueda', 'name_trans' => 'busqueda', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la felicidad', 'name_trans' => 'felicidad', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la constancia', 'name_trans' => 'constancia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la religión', 'name_trans' => 'religion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la fe', 'name_trans' => 'fe', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la lucha', 'name_trans' => 'lucha', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la creación', 'name_trans' => 'creacion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el odio', 'name_trans' => 'odio', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el nacimiento', 'name_trans' => 'nacimiento', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el fracaso', 'name_trans' => 'fracaso', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el pecado', 'name_trans' => 'pecado', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el sacrificio', 'name_trans' => 'sacrificio', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el precio de algo', 'name_trans' => 'precio_de_algo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el descenso', 'name_trans' => 'descenso', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el sufrimiento', 'name_trans' => 'sufrimiento', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el heroismo', 'name_trans' => 'heroismo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el deshonor', 'name_trans' => 'deshonor', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el gobierno', 'name_trans' => 'gobierno', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el desastre', 'name_trans' => 'desastre', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el patriotismo', 'name_trans' => 'patriotismo', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el caos', 'name_trans' => 'caos', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el juicio', 'name_trans' => 'juicio', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el prejuicio', 'name_trans' => 'prejuicio', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el hogar', 'name_trans' => 'hogar', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el aislamiento', 'name_trans' => 'aislamiento', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el engaño', 'name_trans' => 'engano', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el sentido de la vida', 'name_trans' => 'sentido_de_la_vida', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el éxito', 'name_trans' => 'exito', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la culpa', 'name_trans' => 'culpa', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la alienación', 'name_trans' => 'alienacion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la traición', 'name_trans' => 'traicion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la amistad', 'name_trans' => 'amistad', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la fama', 'name_trans' => 'fama', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la madurez', 'name_trans' => 'madurez', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la niñez', 'name_trans' => 'ninez', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la adolescencia', 'name_trans' => 'adolescencia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la paz', 'name_trans' => 'paz', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la esperanza', 'name_trans' => 'esperanza', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la desesperanza', 'name_trans' => 'desesperanza', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la vejez', 'name_trans' => 'vejez', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la existencia', 'name_trans' => 'existencia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la ausencia', 'name_trans' => 'ausencia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la ascensión', 'name_trans' => 'ascension', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la nación', 'name_trans' => 'nacion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la existencia de Dios', 'name_trans' => 'existencia_de_dios', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la familia', 'name_trans' => 'familia', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la soledad', 'name_trans' => 'soledad', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el cautiverio', 'name_trans' => 'cautiverio', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la redención', 'name_trans' => 'redencion', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el autoconocimiento', 'name_trans' => 'autoconocimiento', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el amor', 'name_trans' => 'amor', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la venganza', 'name_trans' => 'venganza', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'el poder', 'name_trans' => 'poder', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la riqueza', 'name_trans' => 'riqueza', 'generico' => 1],
        ['tipo_id' => 5, 'sexo' => 0, 'name' => 'la enfermedad', 'name_trans' => 'enfermedad', 'generico' => 1],

        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'España', 'name_trans' => 'espana', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Mordor', 'name_trans' => 'mordor', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Escocia', 'name_trans' => 'Escocia', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Indonesia', 'name_trans' => 'Indonesia', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Tasmania', 'name_trans' => 'Tasmania', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Siberia', 'name_trans' => 'Siberia', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'La Toscana', 'name_trans' => 'La_Toscana', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'El Sáhara', 'name_trans' => 'El_Sahara', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Alaska', 'name_trans' => 'Alaska', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'El Himalaya', 'name_trans' => 'El_Himalaya', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Estados Unidos', 'name_trans' => 'Estados_Unidos', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Tanzania', 'name_trans' => 'Tanzania', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'Rivendel', 'name_trans' => 'rivendel', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'París', 'name_trans' => 'Paris', 'generico' => 1],
        ['tipo_id' => 6, 'sexo' => 0, 'name' => 'La Comarca', 'name_trans' => 'la_comarca', 'generico' => 1],
      ]);
    }
}
