<?php

use Illuminate\Database\Seeder;

class OutputsTableSeeder extends Seeder
{
    public function run()
    {
      // #1 => Personajes
      // #2 => Escenarios
      // #3 => Objetos
      // #4 => Situaciones
      // #5 => Temas
      DB::table('outputs')->insert([
        ['frase' => '#1 recuerda un momento triste de su infancia.'],
        ['frase' => '¿Cuál es el mayor triunfo de #1?'],
        ['frase' => '¿Para qué #1 que ha venido al mundo?'],
        ['frase' => '¿Qué objetivos tiene #1? ¿Quién o qué se los impiden?'],
        ['frase' => 'Las ideas de #1 sobre #5 son dadas la vuelta.'],
        ['frase' => '#1 y #1 se ven envueltos en una situación de #4'],
        ['frase' => '#1 se encuentra en una situación de #4'],
        ['frase' => '#1 y #1 se encuentran por primera vez en #2u en #6.'],
        ['frase' => '#1 y #1 se enfrentan a causa de #4u.'],
        ['frase' => '#1 y #1 se despiden en #6.'],
        ['frase' => 'Lo que #1 piensa sobre #1 realmente.'],
        ['frase' => 'Cómo le gustaría a #1 que fuera el mundo.'],
        ['frase' => 'Cómo le gustaría a #1 que fuera #5'],
        ['frase' => '#1 va a #2u'],
        ['frase' => 'Algo sobre sí mism@ que avergüenza a #1'],
        ['frase' => '¿Cómo le gustaría a la familia de #1 que fuera él/ella?'],
        ['frase' => '¿Qué objetos puedes encontrar en #2u?'],
        ['frase' => 'Sucede algo mágico en #2u'],
        ['frase' => '¿Cómo expresa #1 sus sentimientos?'],
        ['frase' => '#1 y #1 se encuentran en #2u'],
        ['frase' => '#1 tiene una habilidad especial.'],
        ['frase' => '¿Qué hace #1 para divertirse?'],
        ['frase' => '#1 actúa de forma ilegal a causa de #4u.'],
        ['frase' => '¿Qué lenguas habla #1?'],
        ['frase' => '¿Cómo se gana #1 la vida?'],
        ['frase' => '¿Cuál fue el primer amor de #1? ¿Qué recuerdos guarda?'],
        ['frase' => '#1 tiene una discapacidad.'],
        ['frase' => '¿Qué resentimientos guarda #1?'],
        ['frase' => '¿Cómo escapa #1 a los problemas?'],
        ['frase' => '¿Qué aprecia #1 de #1?'],
        ['frase' => '¿Qué aprecia #1 de #5?'],
        ['frase' => '¿Qué aprecia #1 de #6?'],
        ['frase' => '¿Qué detesta #1 de #1?'],
        ['frase' => '¿Qué detesta #1 de #5?'],
        ['frase' => '¿Qué detesta #1 de #6?'],
        ['frase' => '¿Cuál es el recuerdo más temprano de #1?'],
        ['frase' => '¿Fue la infancia de #1 feliz?'],
        ['frase' => '¿Cuáles son los recuerdos de la infancia de #1 más determinantes?'],
        ['frase' => 'El primer recuerdo de #1 tiene que ver con #3u en #2u'],
        ['frase' => '¿Tiene #1 estudios?'],
        ['frase' => '¿Con qué tipo de personas se lleva bien #1?'],
        ['frase' => '¿Qué tipo de personas aborrece #1?'],
        ['frase' => '¿Se adhiere #1 a los esterotipos de género?'],
        ['frase' => 'Una lección de vida que #1 no haya aprendido (aún)'],
        ['frase' => 'Un amigo de #1'],
        ['frase' => '¿Cómo se comporta #1 en público? ¿Y en privado?'],
        ['frase' => '¿Qué cambiaría #1 de su vida si pudiera?'],
        ['frase' => '¿Dónde se ha criado #1? ¿En #6?'],
        ['frase' => '¿Dónde vive #1 actualmente?'],
        ['frase' => '¿Tiene #1 hermanos?'],
        ['frase' => '¿Sobre qué tema sabe #1 más?'],
        ['frase' => '¿Qué se le da a #1 peor?'],
        ['frase' => '¿Prefiere #1 el orden o el caos?'],
        ['frase' => '¿Es #1 pasional o racional?'],
        ['frase' => '¿Es #1 culto?'],
        ['frase' => '¿Qué prejuicios tiene #1 sobre #5?'],
        ['frase' => '¿Cómo ha influido #1 en #1?'],
        ['frase' => '¿Qué es lo que #1 más desea?'],
        ['frase' => '¿De qué se arrepiente #1?'],
        ['frase' => '#1 ha sido egoísta a causa de #5'],
        ['frase' => '#1 comete un acto cruel a causa de #4u'],
        ['frase' => '¿Cuál es el mayor temor de #1?'],
        ['frase' => '¿A quién odia #1? ¿A #1?'],
        ['frase' => '¿Qué odia #1? ¿#5?'],
        ['frase' => '#1 siente rencor hacia #1 a causa de #4u'],
        ['frase' => '¿Quién es la persona más importante para #1? ¿#1?'],
        ['frase' => '¿Cuál es el dicho preferido de #1?'],
        ['frase' => '¿Cómo es la familia de #1?'],
        ['frase' => '¿Qué hace #1 en su tiempo libre?'],
        ['frase' => '#1 pasa la mayor parte del tiempo en #2e'],
        ['frase' => '¿Qué siente #1 cuando ve a #1?'],
        ['frase' => '¿Cuál es el apodo de #1? ¿Cómo lo consiguió?'],
        ['frase' => 'Una característica psicológica de #1'],
        ['frase' => 'El escondite de #1 es #2u'],
        ['frase' => '¿Cómo habla #1? ¿Cómo utiliza su voz? ¿Qué transmite?'],
        ['frase' => 'Hay algo extraño en #1, la gente le mira raro'],
        ['frase' => 'Una característica física de #1'],
        ['frase' => 'Una manía de #1'],
        ['frase' => '¿Cuál es el anhelo más profundo de #1?'],
        ['frase' => '¿Qué motiva a #1 a levantarse todos los días?'],
        ['frase' => '¿Qué sueño de la infancia de #1 nunca se cumplió?'],
        ['frase' => '¿Cuáles son las creencias de #1?'],
        ['frase' => '¿Qué es lo peor que #1 ha hecho jamás?'],
        ['frase' => 'Un secreto de #1'],
        ['frase' => '¿Qué desconoce #1 sobre #1?'],
        ['frase' => '#1 sueña con #6'],
        ['frase' => '#1 sueña con #1'],
        ['frase' => '#1 sueña con #4u'],
        ['frase' => '#1 sueña con #3u'],
        ['frase' => '¿Qué desconoce #1 sobre #5?'],
        ['frase' => '¿Qué rechaza #1 sobre #5?'],
        ['frase' => '¿Qué ha retenido a #1 toda su vida?'],
        ['frase' => 'Un hábito de #1'],
        ['frase' => 'Una manía de #1'],
        ['frase' => 'Una rareza de #1'],
        ['frase' => '¿Cuál es la decisión más difícil que ha tomado #1?'],
        ['frase' => '¿Cómo reacciona #1 bajo presión?'],
        ['frase' => '¿Qué opina #1 de #5?'],
        ['frase' => '¿Qué sabe #1 sobre #4e?'],
        ['frase' => '¿Qué le ocasiona rechazo a #1?'],
        ['frase' => 'Una contradicción de #1'],
        ['frase' => '¿Ha estado #1 en #2u?'],
        ['frase' => '¿Tiene #1 #3u?'],
        ['frase' => '¿Para qué necesita #1 #3u?'],
        ['frase' => '¿Tiene #1 #3u mágico/a?'],
        ['frase' => '¿Ha perdido #1 su #3?'],
        ['frase' => '#1 le regala a #1 #3u'],
        ['frase' => '#1 no va a ningún sitio sin su #3 de la suerte'],
        ['frase' => '¿Por qué es #3u el objeto preferido de #1?'],
      ]);
    }
}
